### ISSUE TITLE
Assemble all bios here for a new feature

### ISSUE THREAD

**Issue by the-simian** [okcjs/thunderplains-hexo#13]

**Comment by amandaharlin** [comment]
Jennifer Wadella

Jennifer Wadella has been writing code since before she realized it was a credible career path. She currently works as a web developer at MindMixer and loves building javascript applications and attending hackathons. She is an active member of the KC tech community and the founder of Kansas City Women in Technology(KCWiT), a non-profit aimed at growing the number of women in technology careers in Kansas City. She founded and organizes CoderDojoKC, a program that brings mentors in to teach kids how to code, and is a Tech sHeroes mentor, sits on the Shawnee Mission School District CTE Advisory board, is a committee member of the KC Girls in STEM initiative, and is on the JCCC Young Women in STEM Conference planning committee. She doesn't blog, but she can handle 140 characters - @likeOMGitsFEDAY

**Comment by amandaharlin** [comment]
Josh Bavari

Ever since plugging in to a computer at a young age, Josh has been passionate about learning technology and helping others learn. Since 2006, Josh has worked in a variety of business settings ranging from start ups, medium size businesses, and on to the enterprise level. Currently Josh works for a local start up, RaiseMore, where he is focused on building a platform using technologies such as Ruby, Rails, Javascript, HTML5, and PhoneGap.

**Comment by amandaharlin** [comment]
Jenn Schiffer

Jenn Schiffer is an engineer at Bocoup and creator of make8bitart.com. She enjoys humor and art immensely, as well as working her love of programming, computer science, and the open web into those hobbies.

**Comment by amandaharlin** [comment]
Waylon Flinn

Waylon started out in a town with not so much as a calculus class anywhere in a 50 mile radius and began teaching himself to program when he was 11. He eventually got degrees in Physics and Math and wrote the software they use to test astronauts on the International Space Station. The first game he ever loved was Final Fantasy on the NES. Now he thinks games are the future of the world and he's dedicated his life to making life more fun.

**Comment by amandaharlin** [comment]
Adam Baldwin

The BBS owner, having discovered that some kid had brute-forced his passwords for funsies, declined to press charges against Adam, and instead did the next best thing: offered him a job. Under that long-ago sensei’s tutelage, Adam learned the ways of hacking and of reverse engineering, awakening a love for breaking things.

Adam is adept in assessing and securing Node.js, Ruby on Rails, Django, and PHP web apps, as well as providing expertise on secure application design and performing penetration testing at key project points prior to and after launch.

When he’s not experiencing the beauty of winning, Adam is spending time with his equally lovely family and giving speeches on web security at like all the conferences ever.

**Comment by amandaharlin** [comment]
so i guess we have funky + contra's bios?

**Comment by amandaharlin** [comment]
Jeff French

Jeff French is an experienced developer with a passion for automation, software craftsmanship and good craft beer. A mild mannered developer by day and a hopeless technology junky by night. He has extensive experience in web and mobile application development, deployment automation, and continuous delivery. He constantly strives to learn how new technologies can help solve real world problems. He has been a contributor to such open source projects as MVC Turbine, Shoelace-MVC and Octopus Deploy’s OctoPack. Jeff is an international speaker at technology conferences giving talks on DevOps, Continuous Delivery, Mobile and Web Development, Javascript frameworks and whatever else strikes his interest.

cc @jeff-french is this still good or do you have any updates we should add?

**Comment by amandaharlin** [comment]
Is Gordon's bio in the okcjs email acct? i don't have it, but i do have his photo. cc @the-simian

**Comment by amandaharlin** [comment]
Derick Bailey

Derick Bailey is an entrepreneur, problem solver (and creator? :P ), software developer, screencaster, writer, blogger, speaker and technology leader in central Texas (north of Austin). He runs SignalLeaf.com – the amazingly awesome podcast audio hosting service that everyone should be using, and WatchMeCode.net where he throws down the JavaScript gauntlets to get you up to speed. He has been a professional software developer since the late 90’s, and has been writing code since the late 80’s.

Find me on twitter: @derickbailey, @mutedsolutions, @backbonejsclass

Find me on the web: Muted Solutions, SignalLeaf, WatchMeCode, MarionetteJS, My Github profile, On Google+

Email me: derick@mutedsolutions.com

Check out my products and services, too!

cc @derickbailey is this bio from your [about page](http://derickbailey.com/about/) ok with you? (we'll add the links back in, eep)

**Comment by amandaharlin** [comment]
Tracy Hinds

By evenings and weekends, Cat Herder-in-Chief of PDXNode and CascadiaJS; by day, Web Engineer at Urban Airship; Tracy spends too much time frequenting the internets and inciting tiny revolutions of confidence one encouragement at a time. When she isn't coding JavaScript, organizing, monkeying up rocks/trees or bicycling to and from the glorious amount of tech meetups she organizes and enjoys in Portland--she's talking your ear off about them(or anything else she's read about that day). You have been warned.

**Also recently discovered she enjoys screaming over loud music about Node.js more than most.

cc @hackygolucky is this bio still ok with you? we can update it :-)

**Comment by amandaharlin** [comment]
Jeremy Green

Jeremy is a full stack engineer who has been creating web apps for over 15 years. He's an organizer of the OkcRuby developer group and an active open source contributor. You might also find him drumming, shooting photos, or brewing.

**Comment by amandaharlin** [comment]
Jordan Rousseau

"You know me :)"

cc @jvrousseau lol we need a bio for you

**Comment by amandaharlin** [comment]
Kassandra Perch

I'm an engineering evangelist for RetailMeNot in Austin, TX. When I'm not writing javascript, teaching for Girl Develop It Austin, or building robots, I'm crafting or playing a new video game.

**Comment by amandaharlin** [comment]
@the-simian i think that's it, right? double check with everyone cc'd and also gordon, funkytek and contra

**Comment by hackygolucky** [comment]
@amandaharlin Yeeeeah I should prob tweak it slightly:

By day, Tracy Hinds is a Web Engineer at Urban Airship in NYC; by nights and weekends, Cat Herder of programming events shenanigans.  She frequents the internets and attempts tiny revolutions of confidence--one encouragement at a time. When she isn't coding, organizing, monkeying up rocks/trees or bicycling to and from the glorious amount of tech meetups she can't resist--she's talking your ear off about them(or anything else she's read about that day). You have been warned.

**Also recently discovered she enjoys screaming over loud music about JavaScript more than most.

**Comment by amandaharlin** [comment]
awesome @hackygolucky! :sparkling_heart: :sparkles:

**Comment by the-simian** [comment]
#17 has added many of them, but I'm leaving this open until everyone is happy with their bio

**Comment by jvrousseau** [comment]
@amandaharlin what?? you can't use the one I provided? :)

Jordan is a recovering ActionScript developer who is passionate about open geo and data visualization platforms. Jordan currently works for Weather Decision Technologies. He leads a team of crazy talented developers making the world of weather more accessible. When Jordan isn't making all the JavaScript things, he enjoys breaking builds in Jenkins.

**Comment by the-simian** [comment]
@jvrousseau Not sure why I missed that! Its up!

**Comment by jeff-french** [comment]
Mine looks good. :)

**Comment by vlucas** [comment]
Crap. We forgot to let people know that @jeff-french prefers to be called Jeff American. Don't worry Jeff, we'll get that in for you.

**Comment by mxriverlynn** [comment]
wow, i didn't realize my bio on my own site was so out dated :P

---

Derick Bailey is an entrepreneur, developer, screencaster, writer, blogger, speaker and technology leader in central Texas (north of Austin). He runs a podcast hosting service at [SignalLeaf.com](http://signalleaf.com), and throws down the screencasts at [WatchMeCode.net](http://watchmecode.net). He has been a professional software developer since the late 90’s, and has been writing code since the late 80’s.

In his spare time he builds ridiculous electronic toys with Arduino (and a nearby first aid kit), is 1/3rd of a podcast on being [a developer/entrepreneur](http://entreprogramers.com), gets called a spamming marketer by people on Twitter, and blurts out all of the stupid / funny things he's ever done in his career on [his email newsletter](http://derickbailey.com/email_archive/).

Follow [@derickbailey](http://twitter.com/derickbailey), and keep up with the latest bloggerings and writing at [derickbailey.com](http://derickbailey.com).

**Comment by amandaharlin** [comment]
:+1: thank you! :)

**Comment by the-simian** [comment]
Thank @derickbailey  I'll get this in the site.

**Comment by the-simian** [comment]
@derickbailey  FYI the entreprogramers.com link is down, so I did not include that particular one. otherwise, the changes are live now.

**Comment by the-simian** [comment]
I'm gonna close this, I'm fairly certain we've got most folks, just reopen and assign to me if I missed any.

**Comment by amandaharlin** [comment]
great job @the-simian

**Comment by mxriverlynn** [comment]
@the-simian the http://entreprogrammers.com/ site is back up (haven't been able to figure out why it goes down now and then)

**Comment by the-simian** [comment]
Okay, @derickbailey, I'll add it back in when I can. Thanks for the heads up

**Comment by vlucas** [comment]
It was actually just a typo in the URL. :)

## 

Vance Lucas
http://vancelucas.com
(405) 303-1021

**Comment by the-simian** [comment]
You mean the two m's ? i did catch that. It said something like, unable to establish database connection at the time. It really was down (but now it really is up). :roller_coaster:
